CREATE TABLE income_statements (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    link VARCHAR(255) NOT NULL DEFAULT '',
    final_link VARCHAR(255) NOT NULL DEFAULT '',
    date DATE NOT NULL,
    cost_and_expenses numeric,
    cost_of_revenue numeric,
    depreciation_and_amortization numeric,
    earnings_before_interest_taxes_depreciation_and_amortization numeric,
    general_and_administrative_expenses numeric,
    gross_profit numeric,
    income_before_tax numeric,
    income_tax_expenses numeric,
    interest_expense numeric,
    net_income numeric,
    net_total_other_income_and_expenses numeric,
    operating_expenses numeric,
    operating_income numeric,
    other_expenses numeric,
    research_and_development_expenses numeric,
    revenue numeric,
    selling_and_marketing_expenses numeric,
    selling_general_and_administrative_expenses numeric,
    weighted_average_diluted_shares_outstanding numeric,
    weighted_average_shares_outstanding numeric
);

CREATE TABLE balance_sheet_statements (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    link VARCHAR(255) NOT NULL DEFAULT '',
    final_link VARCHAR(255) NOT NULL DEFAULT '',
    date DATE NOT NULL,
    accumulated_other_comprehensive_income_and_loss numeric,
    accounts_payable numeric,
    cash_and_cash_equivalents numeric,
    cash_and_short_term_investments numeric,
    common_stocks numeric,
    deferred_revenue numeric,
    deferred_revenue_non_current numeric,
    deferred_tax_liabilities_non_current numeric,
    goodwill numeric,
    goodwill_and_intangible_assets numeric,
    intangible_assets numeric,
    inventory numeric,
    long_term_debt numeric,
    long_term_investments numeric,
    net_debt numeric,
    net_receivables numeric,
    other_assets numeric,
    other_current_assets numeric,
    other_current_liabilities numeric,
    other_liabilities numeric,
    other_non_current_assets numeric,
    other_non_current_liabilities numeric,
    other_total_stockholders_equity numeric,
    preferred_stocks numeric,
    property_plant_and_equipment numeric,
    retained_earnings numeric,
    short_term_debt numeric,
    short_term_investments numeric,
    tax_assets numeric,
    tax_payables numeric,
    total_assets numeric,
    total_current_assets numeric,
    total_current_liabilities numeric,
    total_debt numeric,
    total_investments numeric,
    total_liabilities numeric,
    total_liabilities_and_total_equity numeric,
    total_non_current_assets numeric,
    total_non_current_liabilities numeric,
    total_stockholders_equity numeric
);

CREATE TABLE cashflow_statements (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    link VARCHAR(255) NOT NULL DEFAULT '',
    final_link VARCHAR(255) NOT NULL DEFAULT '',
    date DATE NOT NULL,
    acquisitions_net numeric,
    accounts_payable numeric,
    accounts_receivable numeric,
    capital_expenditures numeric,
    cash_beginning_period numeric,
    cash_end_period numeric,
    change_in_working_capital numeric,
    common_stock_issued numeric,
    common_stock_repurchased numeric,
    debt_repayment numeric,
    deferred_income_tax numeric,
    depreciation_and_amortization numeric,
    dividends_paid numeric,
    effect_of_forex_exchange numeric,
    financing_activities_cash_flow numeric,
    free_cash_flow numeric,
    inventory numeric,
    investing_activities_cash_flow numeric,
    investments_in_property_plant_and_equipment numeric,
    net_change_in_cash numeric,
    net_income numeric,
    operating_activities_cash_flow numeric,
    other_financing_activities numeric,
    other_investing_activities numeric,
    other_non_cash_items numeric,
    other_working_capital numeric,
    purchases_of_investments numeric,
    sales_and_maturities_of_investments numeric,
    stock_based_compensation numeric
);

CREATE TABLE rentability_ratios (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    date DATE NOT NULL,
    nopat_roic numeric NOT NULL,
    return_on_assets numeric NOT NULL,
    return_on_capital numeric NOT NULL,
    return_on_common_equity numeric NOT NULL,
    return_on_equity numeric NOT NULL,
    return_on_invested_capital numeric NOT NULL,
    return_on_tangible_assets numeric NOT NULL,
    return_on_total_assets numeric NOT NULL,
    rogic numeric NOT NULL
);

CREATE TABLE liquidity_ratios (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    date DATE NOT NULL,
    cash_ratio numeric NOT NULL,
    current_ratio numeric NOT NULL,
    debt_to_equity_ratio numeric NOT NULL,
    operating_cash_flow_ratio numeric NOT NULL,
    quick_ratio numeric NOT NULL
);
CREATE TABLE margin_ratios (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    date DATE NOT NULL,
    free_cash_flow_equity_to_net_income numeric NOT NULL,
    free_cash_flow_margin numeric NOT NULL,
    gross_margin numeric NOT NULL,
    net_income_margin numeric NOT NULL,
    owners_earnings_to_net_income numeric NOT NULL,
    unlevered_free_cash_flow_to_net_income numeric NOT NULL,
    unlevered_free_cash_flow_to_operating_income numeric NOT NULL,
    unlevered_free_cash_flow_ebit_to_net_income numeric NOT NULL
);
CREATE TABLE free_cashflow_ratios (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    date DATE NOT NULL,
    free_cash_flow numeric NOT NULL,
    free_cash_flow_equity numeric NOT NULL,
    unlevered_free_cash_flow numeric NOT NULL,
    unlevered_free_cash_flow_ebit numeric NOT NULL,
    owners_earnings numeric NOT NULL
);

CREATE TABLE per_share_values (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    date DATE NOT NULL,
    book_value_per_share numeric NOT NULL,
    capital_expenditure_per_share numeric NOT NULL,
    cash_per_share numeric NOT NULL,
    earnings_per_share numeric NOT NULL,
    free_cash_flow_per_share numeric NOT NULL,
    operating_cash_flow_per_share numeric NOT NULL,
    sales_per_share numeric NOT NULL,
    tangible_book_value_per_share numeric NOT NULL,
    total_assets_per_share numeric NOT NULL
);
CREATE TABLE non_gaap_figures (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    date DATE NOT NULL,
    average_accounts_payable numeric NOT NULL,
    average_inventory numeric NOT NULL,
    dividend_yield numeric NOT NULL,
    earnings_yield numeric NOT NULL,
    effective_tax_rate numeric NOT NULL,
    free_cash_flow_yield numeric NOT NULL,
    income_quality numeric NOT NULL,
    invested_capital numeric NOT NULL,
    market_capitalization numeric NOT NULL,
    net_current_asset_value numeric NOT NULL,
    net_operating_profit_after_tax numeric NOT NULL,
    normalized_income numeric NOT NULL,
    payout_ratio numeric NOT NULL,
    retention_ratio numeric NOT NULL,
    tangible_assets numeric NOT NULL
);
CREATE TABLE operation_risk_ratios (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    date DATE NOT NULL,
    asset_coverage_ratio numeric NOT NULL,
    cash_coverage numeric NOT NULL,
    cash_flow_coverage_ratios numeric NOT NULL,
    debt_ratio numeric NOT NULL,
    debt_service_coverage numeric NOT NULL,
    interest_coverage numeric NOT NULL,
    long_term_debt_to_capitalization numeric NOT NULL,
    operating_cash_flow_ratio numeric NOT NULL,
    total_debt_to_capitalization numeric NOT NULL
);
CREATE TABLE enterprise_value_ratios (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    date DATE NOT NULL,
    company_equity_multiplier numeric NOT NULL,
    enterprise_value numeric NOT NULL,
    enterprise_value_to_free_cash_flow numeric NOT NULL,
    enterprise_value_to_operating_cash_flow numeric NOT NULL,
    enterprise_value_to_sales numeric NOT NULL,
    enterprise_value_multiple numeric NOT NULL,
    market_capitalization numeric NOT NULL
);
CREATE TABLE company_growth (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    date DATE NOT NULL,
    capital_expenditure_growth numeric NOT NULL,
    cost_of_revenue_growth numeric NOT NULL,
    earnings_per_share_growth numeric NOT NULL,
    free_cash_flow_growth numeric NOT NULL,
    net_income_growth numeric NOT NULL,
    operating_expenses_growth numeric NOT NULL,
    owners_earnings_growth numeric NOT NULL,
    research_and_development_expenses_growth numeric NOT NULL,
    revenue_growth numeric NOT NULL,
    shares_buyback numeric NOT NULL
);
CREATE TABLE efficiency_ratios (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    date DATE NOT NULL,
    accounts_payable_turnover numeric NOT NULL,
    asset_turnover numeric NOT NULL,
    cash_conversion_cycle numeric NOT NULL,
    cash_conversion_ratio numeric NOT NULL,
    days_inventory_outstanding numeric NOT NULL,
    days_payables_outstanding numeric NOT NULL,
    days_sales_outstanding numeric NOT NULL,
    fixed_asset_turnover numeric NOT NULL,
    free_cash_flow_to_operating_cash_flow numeric NOT NULL,
    inventory_turnover numeric NOT NULL,
    operating_cycle numeric NOT NULL
);
CREATE TABLE price_to_ratios (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    reported_currency_id BIGINT REFERENCES currencies(id) ON DELETE SET NULL,
    period_id BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    is_ttm BOOLEAN NOT NULL DEFAULT FALSE,
    from_average BOOLEAN NOT NULL DEFAULT FALSE,
    date DATE NOT NULL,
    price_to_book_value numeric NOT NULL,
    price_to_cash_flow numeric NOT NULL,
    price_to_earnings numeric NOT NULL,
    price_to_earnings_growth numeric NOT NULL,
    price_to_free_cash_flow numeric NOT NULL,
    price_to_operating_cash_flow numeric,
    price_to_sales numeric NOT NULL,
    price_to_tangible_assets numeric NOT NULL,
    price_to_total_assets numeric NOT NULL
);
